[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]

# Custom linker script
rustflags = [
   "-C", "link-arg=-Tlinker.ld",     # Use your own linker.ld
  "-C", "link-arg=--nmagic",        # Prevent page alignment
  "-C", "link-arg=--no-pie",        # Disable PIE
  "-C", "link-arg=-nostartfiles",   # Avoid system startup code
  "-C", "relocation-model=static",
  "-C", "target-feature=+crt-static"
]
